// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: base.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Hazkey_StatusCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case success // = 1
  case failed // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .success
    case 2: self = .failed
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .success: return 1
    case .failed: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Hazkey_StatusCode] = [
    .unspecified,
    .success,
    .failed,
  ]

}

nonisolated struct Hazkey_RequestEnvelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var payload: Hazkey_RequestEnvelope.OneOf_Payload? = nil

  var newComposingText: Hazkey_Commands_NewComposingText {
    get {
      if case .newComposingText(let v)? = payload {return v}
      return Hazkey_Commands_NewComposingText()
    }
    set {payload = .newComposingText(newValue)}
  }

  var setContext: Hazkey_Commands_SetContext {
    get {
      if case .setContext(let v)? = payload {return v}
      return Hazkey_Commands_SetContext()
    }
    set {payload = .setContext(newValue)}
  }

  var inputChar: Hazkey_Commands_InputChar {
    get {
      if case .inputChar(let v)? = payload {return v}
      return Hazkey_Commands_InputChar()
    }
    set {payload = .inputChar(newValue)}
  }

  var modifierEvent: Hazkey_Commands_ModifierEvent {
    get {
      if case .modifierEvent(let v)? = payload {return v}
      return Hazkey_Commands_ModifierEvent()
    }
    set {payload = .modifierEvent(newValue)}
  }

  var moveCursor: Hazkey_Commands_MoveCursor {
    get {
      if case .moveCursor(let v)? = payload {return v}
      return Hazkey_Commands_MoveCursor()
    }
    set {payload = .moveCursor(newValue)}
  }

  var prefixComplete: Hazkey_Commands_PrefixComplete {
    get {
      if case .prefixComplete(let v)? = payload {return v}
      return Hazkey_Commands_PrefixComplete()
    }
    set {payload = .prefixComplete(newValue)}
  }

  var deleteLeft: Hazkey_Commands_DeleteLeft {
    get {
      if case .deleteLeft(let v)? = payload {return v}
      return Hazkey_Commands_DeleteLeft()
    }
    set {payload = .deleteLeft(newValue)}
  }

  var deleteRight: Hazkey_Commands_DeleteRight {
    get {
      if case .deleteRight(let v)? = payload {return v}
      return Hazkey_Commands_DeleteRight()
    }
    set {payload = .deleteRight(newValue)}
  }

  var getComposingString: Hazkey_Commands_GetComposingString {
    get {
      if case .getComposingString(let v)? = payload {return v}
      return Hazkey_Commands_GetComposingString()
    }
    set {payload = .getComposingString(newValue)}
  }

  var getHiraganaWithCursor: Hazkey_Commands_GetHiraganaWithCursor {
    get {
      if case .getHiraganaWithCursor(let v)? = payload {return v}
      return Hazkey_Commands_GetHiraganaWithCursor()
    }
    set {payload = .getHiraganaWithCursor(newValue)}
  }

  var getCandidates: Hazkey_Commands_GetCandidates {
    get {
      if case .getCandidates(let v)? = payload {return v}
      return Hazkey_Commands_GetCandidates()
    }
    set {payload = .getCandidates(newValue)}
  }

  var getCurrentInputMode: Hazkey_Commands_GetCurrentInputModeInfo {
    get {
      if case .getCurrentInputMode(let v)? = payload {return v}
      return Hazkey_Commands_GetCurrentInputModeInfo()
    }
    set {payload = .getCurrentInputMode(newValue)}
  }

  var saveLearningData: Hazkey_Commands_SaveLearningData {
    get {
      if case .saveLearningData(let v)? = payload {return v}
      return Hazkey_Commands_SaveLearningData()
    }
    set {payload = .saveLearningData(newValue)}
  }

  var adjustClauseBoundary: Hazkey_Commands_AdjustClauseBoundary {
    get {
      if case .adjustClauseBoundary(let v)? = payload {return v}
      return Hazkey_Commands_AdjustClauseBoundary()
    }
    set {payload = .adjustClauseBoundary(newValue)}
  }

  var acceptPrediction: Hazkey_Commands_AcceptPrediction {
    get {
      if case .acceptPrediction(let v)? = payload {return v}
      return Hazkey_Commands_AcceptPrediction()
    }
    set {payload = .acceptPrediction(newValue)}
  }

  var deleteCandidateLearningData: Hazkey_Commands_DeleteCandidateLearningData {
    get {
      if case .deleteCandidateLearningData(let v)? = payload {return v}
      return Hazkey_Commands_DeleteCandidateLearningData()
    }
    set {payload = .deleteCandidateLearningData(newValue)}
  }

  var toggleZenzai: Hazkey_Commands_ToggleZenzai {
    get {
      if case .toggleZenzai(let v)? = payload {return v}
      return Hazkey_Commands_ToggleZenzai()
    }
    set {payload = .toggleZenzai(newValue)}
  }

  var getConfig: Hazkey_Config_GetConfig {
    get {
      if case .getConfig(let v)? = payload {return v}
      return Hazkey_Config_GetConfig()
    }
    set {payload = .getConfig(newValue)}
  }

  var setConfig: Hazkey_Config_SetConfig {
    get {
      if case .setConfig(let v)? = payload {return v}
      return Hazkey_Config_SetConfig()
    }
    set {payload = .setConfig(newValue)}
  }

  var getDefaultProfile: Hazkey_Config_GetDefaultProfile {
    get {
      if case .getDefaultProfile(let v)? = payload {return v}
      return Hazkey_Config_GetDefaultProfile()
    }
    set {payload = .getDefaultProfile(newValue)}
  }

  var clearAllHistory_p: Hazkey_Config_ClearAllHistory {
    get {
      if case .clearAllHistory_p(let v)? = payload {return v}
      return Hazkey_Config_ClearAllHistory()
    }
    set {payload = .clearAllHistory_p(newValue)}
  }

  var reloadZenzaiModel: Hazkey_Config_ReloadZenzaiModel {
    get {
      if case .reloadZenzaiModel(let v)? = payload {return v}
      return Hazkey_Config_ReloadZenzaiModel()
    }
    set {payload = .reloadZenzaiModel(newValue)}
  }

  var getLearningHistory: Hazkey_Config_GetLearningHistory {
    get {
      if case .getLearningHistory(let v)? = payload {return v}
      return Hazkey_Config_GetLearningHistory()
    }
    set {payload = .getLearningHistory(newValue)}
  }

  var deleteLearningEntries: Hazkey_Config_DeleteLearningEntries {
    get {
      if case .deleteLearningEntries(let v)? = payload {return v}
      return Hazkey_Config_DeleteLearningEntries()
    }
    set {payload = .deleteLearningEntries(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Payload: Equatable, Sendable {
    case newComposingText(Hazkey_Commands_NewComposingText)
    case setContext(Hazkey_Commands_SetContext)
    case inputChar(Hazkey_Commands_InputChar)
    case modifierEvent(Hazkey_Commands_ModifierEvent)
    case moveCursor(Hazkey_Commands_MoveCursor)
    case prefixComplete(Hazkey_Commands_PrefixComplete)
    case deleteLeft(Hazkey_Commands_DeleteLeft)
    case deleteRight(Hazkey_Commands_DeleteRight)
    case getComposingString(Hazkey_Commands_GetComposingString)
    case getHiraganaWithCursor(Hazkey_Commands_GetHiraganaWithCursor)
    case getCandidates(Hazkey_Commands_GetCandidates)
    case getCurrentInputMode(Hazkey_Commands_GetCurrentInputModeInfo)
    case saveLearningData(Hazkey_Commands_SaveLearningData)
    case adjustClauseBoundary(Hazkey_Commands_AdjustClauseBoundary)
    case acceptPrediction(Hazkey_Commands_AcceptPrediction)
    case deleteCandidateLearningData(Hazkey_Commands_DeleteCandidateLearningData)
    case toggleZenzai(Hazkey_Commands_ToggleZenzai)
    case getConfig(Hazkey_Config_GetConfig)
    case setConfig(Hazkey_Config_SetConfig)
    case getDefaultProfile(Hazkey_Config_GetDefaultProfile)
    case clearAllHistory_p(Hazkey_Config_ClearAllHistory)
    case reloadZenzaiModel(Hazkey_Config_ReloadZenzaiModel)
    case getLearningHistory(Hazkey_Config_GetLearningHistory)
    case deleteLearningEntries(Hazkey_Config_DeleteLearningEntries)

  }

  init() {}
}

nonisolated struct Hazkey_ResponseEnvelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var status: Hazkey_StatusCode = .unspecified

  var errorMessage: String = String()

  var payload: Hazkey_ResponseEnvelope.OneOf_Payload? = nil

  var text: String {
    get {
      if case .text(let v)? = payload {return v}
      return String()
    }
    set {payload = .text(newValue)}
  }

  var candidates: Hazkey_Commands_CandidatesResult {
    get {
      if case .candidates(let v)? = payload {return v}
      return Hazkey_Commands_CandidatesResult()
    }
    set {payload = .candidates(newValue)}
  }

  var textWithCursor: Hazkey_Commands_TextWithCursor {
    get {
      if case .textWithCursor(let v)? = payload {return v}
      return Hazkey_Commands_TextWithCursor()
    }
    set {payload = .textWithCursor(newValue)}
  }

  var currentInputModeInfo: Hazkey_Commands_CurrentInputModeInfo {
    get {
      if case .currentInputModeInfo(let v)? = payload {return v}
      return Hazkey_Commands_CurrentInputModeInfo()
    }
    set {payload = .currentInputModeInfo(newValue)}
  }

  var clauseBoundaryResult: Hazkey_Commands_ClauseBoundaryResult {
    get {
      if case .clauseBoundaryResult(let v)? = payload {return v}
      return Hazkey_Commands_ClauseBoundaryResult()
    }
    set {payload = .clauseBoundaryResult(newValue)}
  }

  var deleteCandidateLearningDataResult: Hazkey_Commands_DeleteCandidateLearningDataResult {
    get {
      if case .deleteCandidateLearningDataResult(let v)? = payload {return v}
      return Hazkey_Commands_DeleteCandidateLearningDataResult()
    }
    set {payload = .deleteCandidateLearningDataResult(newValue)}
  }

  var toggleZenzaiResult: Hazkey_Commands_ToggleZenzaiResult {
    get {
      if case .toggleZenzaiResult(let v)? = payload {return v}
      return Hazkey_Commands_ToggleZenzaiResult()
    }
    set {payload = .toggleZenzaiResult(newValue)}
  }

  var currentConfig: Hazkey_Config_CurrentConfig {
    get {
      if case .currentConfig(let v)? = payload {return v}
      return Hazkey_Config_CurrentConfig()
    }
    set {payload = .currentConfig(newValue)}
  }

  var getLearningHistoryResult: Hazkey_Config_GetLearningHistoryResult {
    get {
      if case .getLearningHistoryResult(let v)? = payload {return v}
      return Hazkey_Config_GetLearningHistoryResult()
    }
    set {payload = .getLearningHistoryResult(newValue)}
  }

  var deleteLearningEntriesResult: Hazkey_Config_DeleteLearningEntriesResult {
    get {
      if case .deleteLearningEntriesResult(let v)? = payload {return v}
      return Hazkey_Config_DeleteLearningEntriesResult()
    }
    set {payload = .deleteLearningEntriesResult(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Payload: Equatable, Sendable {
    case text(String)
    case candidates(Hazkey_Commands_CandidatesResult)
    case textWithCursor(Hazkey_Commands_TextWithCursor)
    case currentInputModeInfo(Hazkey_Commands_CurrentInputModeInfo)
    case clauseBoundaryResult(Hazkey_Commands_ClauseBoundaryResult)
    case deleteCandidateLearningDataResult(Hazkey_Commands_DeleteCandidateLearningDataResult)
    case toggleZenzaiResult(Hazkey_Commands_ToggleZenzaiResult)
    case currentConfig(Hazkey_Config_CurrentConfig)
    case getLearningHistoryResult(Hazkey_Config_GetLearningHistoryResult)
    case deleteLearningEntriesResult(Hazkey_Config_DeleteLearningEntriesResult)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "hazkey"

nonisolated extension Hazkey_StatusCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNSPECIFIED\0\u{1}SUCCESS\0\u{1}FAILED\0")
}

nonisolated extension Hazkey_RequestEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestEnvelope"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}new_composing_text\0\u{3}set_context\0\u{3}input_char\0\u{3}modifier_event\0\u{3}move_cursor\0\u{3}prefix_complete\0\u{3}delete_left\0\u{3}delete_right\0\u{3}get_composing_string\0\u{3}get_hiragana_with_cursor\0\u{3}get_candidates\0\u{3}get_current_input_mode\0\u{3}save_learning_data\0\u{3}adjust_clause_boundary\0\u{3}accept_prediction\0\u{3}delete_candidate_learning_data\0\u{3}toggle_zenzai\0\u{4}S\u{1}get_config\0\u{3}set_config\0\u{3}get_default_profile\0\u{3}clear_all_history\0\u{3}reload_zenzai_model\0\u{3}get_learning_history\0\u{3}delete_learning_entries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Hazkey_Commands_NewComposingText?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .newComposingText(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .newComposingText(v)
        }
      }()
      case 2: try {
        var v: Hazkey_Commands_SetContext?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .setContext(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .setContext(v)
        }
      }()
      case 3: try {
        var v: Hazkey_Commands_InputChar?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .inputChar(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .inputChar(v)
        }
      }()
      case 4: try {
        var v: Hazkey_Commands_ModifierEvent?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .modifierEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .modifierEvent(v)
        }
      }()
      case 5: try {
        var v: Hazkey_Commands_MoveCursor?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .moveCursor(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .moveCursor(v)
        }
      }()
      case 6: try {
        var v: Hazkey_Commands_PrefixComplete?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .prefixComplete(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .prefixComplete(v)
        }
      }()
      case 7: try {
        var v: Hazkey_Commands_DeleteLeft?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .deleteLeft(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .deleteLeft(v)
        }
      }()
      case 8: try {
        var v: Hazkey_Commands_DeleteRight?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .deleteRight(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .deleteRight(v)
        }
      }()
      case 9: try {
        var v: Hazkey_Commands_GetComposingString?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getComposingString(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getComposingString(v)
        }
      }()
      case 10: try {
        var v: Hazkey_Commands_GetHiraganaWithCursor?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getHiraganaWithCursor(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getHiraganaWithCursor(v)
        }
      }()
      case 11: try {
        var v: Hazkey_Commands_GetCandidates?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getCandidates(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getCandidates(v)
        }
      }()
      case 12: try {
        var v: Hazkey_Commands_GetCurrentInputModeInfo?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getCurrentInputMode(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getCurrentInputMode(v)
        }
      }()
      case 13: try {
        var v: Hazkey_Commands_SaveLearningData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .saveLearningData(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .saveLearningData(v)
        }
      }()
      case 14: try {
        var v: Hazkey_Commands_AdjustClauseBoundary?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .adjustClauseBoundary(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .adjustClauseBoundary(v)
        }
      }()
      case 15: try {
        var v: Hazkey_Commands_AcceptPrediction?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .acceptPrediction(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .acceptPrediction(v)
        }
      }()
      case 16: try {
        var v: Hazkey_Commands_DeleteCandidateLearningData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .deleteCandidateLearningData(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .deleteCandidateLearningData(v)
        }
      }()
      case 17: try {
        var v: Hazkey_Commands_ToggleZenzai?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .toggleZenzai(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .toggleZenzai(v)
        }
      }()
      case 100: try {
        var v: Hazkey_Config_GetConfig?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getConfig(v)
        }
      }()
      case 101: try {
        var v: Hazkey_Config_SetConfig?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .setConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .setConfig(v)
        }
      }()
      case 102: try {
        var v: Hazkey_Config_GetDefaultProfile?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getDefaultProfile(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getDefaultProfile(v)
        }
      }()
      case 103: try {
        var v: Hazkey_Config_ClearAllHistory?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clearAllHistory_p(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clearAllHistory_p(v)
        }
      }()
      case 104: try {
        var v: Hazkey_Config_ReloadZenzaiModel?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .reloadZenzaiModel(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .reloadZenzaiModel(v)
        }
      }()
      case 105: try {
        var v: Hazkey_Config_GetLearningHistory?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getLearningHistory(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getLearningHistory(v)
        }
      }()
      case 106: try {
        var v: Hazkey_Config_DeleteLearningEntries?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .deleteLearningEntries(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .deleteLearningEntries(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .newComposingText?: try {
      guard case .newComposingText(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .setContext?: try {
      guard case .setContext(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .inputChar?: try {
      guard case .inputChar(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .modifierEvent?: try {
      guard case .modifierEvent(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .moveCursor?: try {
      guard case .moveCursor(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .prefixComplete?: try {
      guard case .prefixComplete(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .deleteLeft?: try {
      guard case .deleteLeft(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .deleteRight?: try {
      guard case .deleteRight(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .getComposingString?: try {
      guard case .getComposingString(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .getHiraganaWithCursor?: try {
      guard case .getHiraganaWithCursor(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .getCandidates?: try {
      guard case .getCandidates(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .getCurrentInputMode?: try {
      guard case .getCurrentInputMode(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .saveLearningData?: try {
      guard case .saveLearningData(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .adjustClauseBoundary?: try {
      guard case .adjustClauseBoundary(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }()
    case .acceptPrediction?: try {
      guard case .acceptPrediction(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
    }()
    case .deleteCandidateLearningData?: try {
      guard case .deleteCandidateLearningData(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
    }()
    case .toggleZenzai?: try {
      guard case .toggleZenzai(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
    }()
    case .getConfig?: try {
      guard case .getConfig(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
    }()
    case .setConfig?: try {
      guard case .setConfig(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 101)
    }()
    case .getDefaultProfile?: try {
      guard case .getDefaultProfile(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 102)
    }()
    case .clearAllHistory_p?: try {
      guard case .clearAllHistory_p(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 103)
    }()
    case .reloadZenzaiModel?: try {
      guard case .reloadZenzaiModel(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 104)
    }()
    case .getLearningHistory?: try {
      guard case .getLearningHistory(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 105)
    }()
    case .deleteLearningEntries?: try {
      guard case .deleteLearningEntries(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 106)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_RequestEnvelope, rhs: Hazkey_RequestEnvelope) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_ResponseEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResponseEnvelope"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{3}error_message\0\u{1}text\0\u{1}candidates\0\u{3}text_with_cursor\0\u{3}current_input_mode_info\0\u{3}clause_boundary_result\0\u{3}delete_candidate_learning_data_result\0\u{3}toggle_zenzai_result\0\u{4}[\u{1}current_config\0\u{3}get_learning_history_result\0\u{3}delete_learning_entries_result\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.payload != nil {try decoder.handleConflictingOneOf()}
          self.payload = .text(v)
        }
      }()
      case 4: try {
        var v: Hazkey_Commands_CandidatesResult?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .candidates(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .candidates(v)
        }
      }()
      case 5: try {
        var v: Hazkey_Commands_TextWithCursor?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .textWithCursor(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .textWithCursor(v)
        }
      }()
      case 6: try {
        var v: Hazkey_Commands_CurrentInputModeInfo?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .currentInputModeInfo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .currentInputModeInfo(v)
        }
      }()
      case 7: try {
        var v: Hazkey_Commands_ClauseBoundaryResult?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clauseBoundaryResult(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clauseBoundaryResult(v)
        }
      }()
      case 8: try {
        var v: Hazkey_Commands_DeleteCandidateLearningDataResult?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .deleteCandidateLearningDataResult(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .deleteCandidateLearningDataResult(v)
        }
      }()
      case 9: try {
        var v: Hazkey_Commands_ToggleZenzaiResult?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .toggleZenzaiResult(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .toggleZenzaiResult(v)
        }
      }()
      case 100: try {
        var v: Hazkey_Config_CurrentConfig?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .currentConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .currentConfig(v)
        }
      }()
      case 101: try {
        var v: Hazkey_Config_GetLearningHistoryResult?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getLearningHistoryResult(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getLearningHistoryResult(v)
        }
      }()
      case 102: try {
        var v: Hazkey_Config_DeleteLearningEntriesResult?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .deleteLearningEntriesResult(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .deleteLearningEntriesResult(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 2)
    }
    switch self.payload {
    case .text?: try {
      guard case .text(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case .candidates?: try {
      guard case .candidates(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .textWithCursor?: try {
      guard case .textWithCursor(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .currentInputModeInfo?: try {
      guard case .currentInputModeInfo(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .clauseBoundaryResult?: try {
      guard case .clauseBoundaryResult(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .deleteCandidateLearningDataResult?: try {
      guard case .deleteCandidateLearningDataResult(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .toggleZenzaiResult?: try {
      guard case .toggleZenzaiResult(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .currentConfig?: try {
      guard case .currentConfig(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
    }()
    case .getLearningHistoryResult?: try {
      guard case .getLearningHistoryResult(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 101)
    }()
    case .deleteLearningEntriesResult?: try {
      guard case .deleteLearningEntriesResult(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 102)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_ResponseEnvelope, rhs: Hazkey_ResponseEnvelope) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
