// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: commands.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// 新しい入力 (組成) を開始する
///
/// 入力中のテキスト・候補リスト・Zenzai用の文脈・直接入力モードをリセットし、この接続の変換セッションも破棄する
///
/// - Note: 前回の組成で作った変換結果を再利用しないため、同じ読みでも新たに学習した候補が正しく反映される
nonisolated struct Hazkey_Commands_NewComposingText: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// カーソルの左側にある文脈 (確定済みの文字列) を、Zenzaiの変換に使う文脈として設定する
///
/// - Note: 文脈を使うかどうかは、プロファイルの[zenzai_contextual_mode]で決まる
nonisolated struct Hazkey_Commands_SetContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// カーソル周辺の文字列 (surrounding text)
  var context: String = String()

  /// context内のカーソル位置 (文字数単位)、この位置より左側が文脈になる (範囲外は0〜文字数に丸められる)
  var anchor: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 1文字を入力中テキストのカーソル位置へ挿入する
///
/// 直接入力モードではそのまま挿入し、通常の入力ではキーマップと入力テーブル (ローマ字・かな等) に従って変換する
nonisolated struct Hazkey_Commands_InputChar: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 入力する文字 (先頭の1文字だけを使う)
  var text: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 修飾キーの押下・解放をサーバへ通知する
///
/// [Shift]キーを単体で短く押して離すと、通常入力と直接入力 (英字) を切り替える
///
/// - Note: 500[ms]以上の長押しや、他のキーと組み合わせた場合は切り替えない
nonisolated struct Hazkey_Commands_ModifierEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 対象の修飾キー
  var modType: Hazkey_Commands_ModifierEvent.ModifierType = .unspecified

  /// イベントの種類
  var eventType: Hazkey_Commands_ModifierEvent.EventType = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// 対象の修飾キー
  nonisolated enum ModifierType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// 未設定 (エラーとして扱う)
    case unspecified // = 0

    /// [Shift]キー
    case shift // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .shift
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .shift: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Commands_ModifierEvent.ModifierType] = [
      .unspecified,
      .shift,
    ]

  }

  /// 修飾キーのイベントの種類
  nonisolated enum EventType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// 未設定 (エラーとして扱う)
    case unspecified // = 0

    /// 押下した
    case press // = 1

    /// 単体で押下したまま離した (短押しなら入力モードを切り替える)
    case release // = 2

    /// 他のキーと組み合わせて離した (入力モードは切り替えない)
    case cancel // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .press
      case 2: self = .release
      case 3: self = .cancel
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .press: return 1
      case .release: return 2
      case .cancel: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Commands_ModifierEvent.EventType] = [
      .unspecified,
      .press,
      .release,
      .cancel,
    ]

  }

  init() {}
}

/// 入力中テキスト内でカーソルを移動する
nonisolated struct Hazkey_Commands_MoveCursor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 移動量 (文字数単位、負の値で左、正の値で右へ移動する)
  var offset: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 文節の区切り位置を調整し、調整後の候補を返す (既定のキーは[Shift] + [Left] / [Shift] + [Right])
///
/// - Note: 移動量は、先頭の1文字から入力中テキストの末尾までの範囲に丸められる
nonisolated struct Hazkey_Commands_AdjustClauseBoundary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 区切り位置の移動量 (文字数単位、負の値で短く、正の値で長くする)
  var offset: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 候補を選び、その候補がカバーする読みの分だけ確定する
///
/// 残りの読みは入力中テキストとして残り、続けて変換できる
///
/// - Note: 変換エンジンの候補を確定した場合は、学習データも更新する (ユーザ辞書・日付・かな数字・絵文字の候補は学習しない)
nonisolated struct Hazkey_Commands_PrefixComplete: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 候補リスト内の対象候補の位置
  var index: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 予測候補を、先頭部分の表記として固定する
///
/// 候補の読みのうち未入力の残りを入力中テキストに追加する
///
/// 固定した表記は、以降のZenzai変換で先頭に必ず来る表記として扱われる
///
/// - Note: 既定のホットキーは[F5]キー
/// - Important: PrefixCompleteとは異なり、文字列をアプリケーションへ確定 (コミット) しない
nonisolated struct Hazkey_Commands_AcceptPrediction: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 候補リスト内の対象候補の位置
  var index: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// フォーカス中の候補について、学習データ (AzooKeyの学習メモリ) を削除して、候補リストを作り直す
///
/// 読みと表記が同じであれば、品詞ID (CID) だけが異なる学習エントリも全て削除する
///
/// - Note: 既定のホットキーは[Ctrl] + [D]キー
nonisolated struct Hazkey_Commands_DeleteCandidateLearningData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 候補リスト内の対象候補の位置
  var index: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// DeleteCandidateLearningDataの結果
nonisolated struct Hazkey_Commands_DeleteCandidateLearningDataResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 削除した学習エントリの数 (学習データを持たない候補では0)
  var deletedCount: UInt32 = 0

  /// 削除後に作り直した候補リスト
  var candidates: Hazkey_Commands_CandidatesResult {
    get {_candidates ?? Hazkey_Commands_CandidatesResult()}
    set {_candidates = newValue}
  }
  /// Returns true if `candidates` has been explicitly set.
  var hasCandidates: Bool {self._candidates != nil}
  /// Clears the value of `candidates`. Subsequent reads from it will return its default value.
  mutating func clearCandidates() {self._candidates = nil}

  /// 入力中テキスト全体のひらがな
  var hiragana: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _candidates: Hazkey_Commands_CandidatesResult? = nil
}

/// カーソルの左の1文字を削除する ([BackSpace]キー)
nonisolated struct Hazkey_Commands_DeleteLeft: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// カーソルの右の1文字を削除する ([Delete]キー)
nonisolated struct Hazkey_Commands_DeleteRight: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 入力中テキストを、指定した文字種へ変換して取得する
///
/// ファンクションキー ([F6]〜[F10]キー) や[Ctrl] + [U] / [I] / [O] / [P] / [T]キーによる直接変換で使う
nonisolated struct Hazkey_Commands_GetComposingString: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 取得する文字種
  var charType: Hazkey_Commands_GetComposingString.CharType = .hiragana

  /// 現在表示中の文字列 (英字では、これと比べて小文字 → 大文字 → 先頭だけ大文字の順に切り替える)
  var currentPreedit: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// 取得する文字種
  nonisolated enum CharType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// ひらがな
    case hiragana // = 0

    /// 全角カタカナ
    case katakanaFull // = 1

    /// 半角カタカナ
    case katakanaHalf // = 2

    /// 全角英字
    case alphabetFull // = 3

    /// 半角英字
    case alphabetHalf // = 4
    case UNRECOGNIZED(Int)

    init() {
      self = .hiragana
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .hiragana
      case 1: self = .katakanaFull
      case 2: self = .katakanaHalf
      case 3: self = .alphabetFull
      case 4: self = .alphabetHalf
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .hiragana: return 0
      case .katakanaFull: return 1
      case .katakanaHalf: return 2
      case .alphabetFull: return 3
      case .alphabetHalf: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Commands_GetComposingString.CharType] = [
      .hiragana,
      .katakanaFull,
      .katakanaHalf,
      .alphabetFull,
      .alphabetHalf,
    ]

  }

  init() {}
}

/// 入力中のひらがなを、カーソルの前・カーソル上・カーソルの後の3つに分けて取得する
///
/// - Note: 補助表示を出すかどうかの判断はフロントエンドが行うため、サーバは設定に関係なく常に実際の値を返す
nonisolated struct Hazkey_Commands_GetHiraganaWithCursor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 入力中テキストの候補リストを取得する
nonisolated struct Hazkey_Commands_GetCandidates: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// trueなら入力中に表示する予測候補 (サジェスト)、falseなら[Space]キー等による通常の変換候補
  var isSuggest: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 現在の入力モード (通常 / 直接入力) を取得する
nonisolated struct Hazkey_Commands_GetCurrentInputModeInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 未保存の学習データをファイルへ保存する
///
/// - Note: 学習データは全ての接続で共有されるため、他の接続で入力した未保存の学習データも保存される
nonisolated struct Hazkey_Commands_SaveLearningData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 現在のプロファイルのZenzai (ニューラル変換) の有効 / 無効だけを切り替える
///
/// 入力中のテキストや候補リストはリセットしない
///
/// - Note: 既定のホットキーは[Control] + [Alt] + [Z]キー
nonisolated struct Hazkey_Commands_ToggleZenzai: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// ToggleZenzaiの結果
nonisolated struct Hazkey_Commands_ToggleZenzaiResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 切り替え後にZenzaiが有効ならtrue
  var enabled: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 文字列の戻り値
nonisolated struct Hazkey_Commands_Text: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 文字列
  var text: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// カーソル位置で3つに分けた文字列
nonisolated struct Hazkey_Commands_TextWithCursor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// カーソルより前の文字列 (フィールド名のtypoは互換性のため維持する)
  var beforeCursosr: String = String()

  /// カーソル上の1文字 (カーソルが末尾にある場合は空)
  var onCursor: String = String()

  /// カーソルより後の文字列
  var afterCursor: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 候補リスト
nonisolated struct Hazkey_Commands_CandidatesResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 候補の一覧 (表示順)
  var candidates: [Hazkey_Commands_CandidatesResult.Candidate] = []

  /// ライブ変換で入力中テキストの代わりに表示する文字列 (ライブ変換しない場合は空)
  var liveText: String = String()

  /// live_textに対応する候補のcandidates内の位置 (無い場合は -1)
  var liveTextIndex: Int32 = 0

  /// 1ページに表示する候補数 (予測候補を表示しない設定では 0)
  var pageSize: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// 1つの候補
  nonisolated struct Candidate: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// 候補の表記
    var text: String = String()

    /// この候補でカバーされない残りの読み (ひらがな、読み全体をカバーする場合は空)
    var subHiragana: String = String()

    /// この候補に一致する学習データがAzooKeyの学習メモリにある場合はtrue
    ///
    /// trueの候補にフォーカスすると、補助表示に[削除可]と表示され、学習データ削除ホットキーで削除できる
    ///
    /// - Note: 学習データ削除ホットキーの既定は[Ctrl] + [D]キー
    var hasLearningEntry_p: Bool {
      get {_hasLearningEntry_p ?? false}
      set {_hasLearningEntry_p = newValue}
    }
    /// Returns true if `hasLearningEntry_p` has been explicitly set.
    var hasHasLearningEntry_p: Bool {self._hasLearningEntry_p != nil}
    /// Clears the value of `hasLearningEntry_p`. Subsequent reads from it will return its default value.
    mutating func clearHasLearningEntry_p() {self._hasLearningEntry_p = nil}

    /// サーバが誤字の訂正案として生成した候補である
    var isTypoCorrection: Bool {
      get {_isTypoCorrection ?? false}
      set {_isTypoCorrection = newValue}
    }
    /// Returns true if `isTypoCorrection` has been explicitly set.
    var hasIsTypoCorrection: Bool {self._isTypoCorrection != nil}
    /// Clears the value of `isTypoCorrection`. Subsequent reads from it will return its default value.
    mutating func clearIsTypoCorrection() {self._isTypoCorrection = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _hasLearningEntry_p: Bool? = nil
    fileprivate var _isTypoCorrection: Bool? = nil
  }

  init() {}
}

/// AdjustClauseBoundaryの結果
nonisolated struct Hazkey_Commands_ClauseBoundaryResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 区切り位置を調整した後の候補リスト
  var candidates: Hazkey_Commands_CandidatesResult {
    get {_candidates ?? Hazkey_Commands_CandidatesResult()}
    set {_candidates = newValue}
  }
  /// Returns true if `candidates` has been explicitly set.
  var hasCandidates: Bool {self._candidates != nil}
  /// Clears the value of `candidates`. Subsequent reads from it will return its default value.
  mutating func clearCandidates() {self._candidates = nil}

  /// 入力中テキスト全体のひらがな
  var hiragana: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _candidates: Hazkey_Commands_CandidatesResult? = nil
}

/// 現在の入力モード
nonisolated struct Hazkey_Commands_CurrentInputModeInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 現在の入力モード
  var inputMode: Hazkey_Commands_CurrentInputModeInfo.InputMode = .normal

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// 入力モードの種類
  nonisolated enum InputMode: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// 通常の入力 (かな漢字変換を行う)
    case normal // = 0

    /// 直接入力 (英字をそのまま入力する)
    case direct // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .normal
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .normal
      case 1: self = .direct
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .normal: return 0
      case .direct: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Commands_CurrentInputModeInfo.InputMode] = [
      .normal,
      .direct,
    ]

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "hazkey.commands"

nonisolated extension Hazkey_Commands_NewComposingText: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NewComposingText"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_NewComposingText, rhs: Hazkey_Commands_NewComposingText) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_SetContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SetContext"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0\u{1}anchor\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.context) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.anchor) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.context.isEmpty {
      try visitor.visitSingularStringField(value: self.context, fieldNumber: 1)
    }
    if self.anchor != 0 {
      try visitor.visitSingularInt32Field(value: self.anchor, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_SetContext, rhs: Hazkey_Commands_SetContext) -> Bool {
    if lhs.context != rhs.context {return false}
    if lhs.anchor != rhs.anchor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_InputChar: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InputChar"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_InputChar, rhs: Hazkey_Commands_InputChar) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_ModifierEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ModifierEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}mod_type\0\u{3}event_type\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.modType) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.eventType) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.modType != .unspecified {
      try visitor.visitSingularEnumField(value: self.modType, fieldNumber: 1)
    }
    if self.eventType != .unspecified {
      try visitor.visitSingularEnumField(value: self.eventType, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_ModifierEvent, rhs: Hazkey_Commands_ModifierEvent) -> Bool {
    if lhs.modType != rhs.modType {return false}
    if lhs.eventType != rhs.eventType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_ModifierEvent.ModifierType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MODIFIER_TYPE_UNSPECIFIED\0\u{1}SHIFT\0")
}

nonisolated extension Hazkey_Commands_ModifierEvent.EventType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0EVENT_TYPE_UNSPECIFIED\0\u{1}PRESS\0\u{1}RELEASE\0\u{1}CANCEL\0")
}

nonisolated extension Hazkey_Commands_MoveCursor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MoveCursor"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}offset\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.offset) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.offset != 0 {
      try visitor.visitSingularInt32Field(value: self.offset, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_MoveCursor, rhs: Hazkey_Commands_MoveCursor) -> Bool {
    if lhs.offset != rhs.offset {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_AdjustClauseBoundary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AdjustClauseBoundary"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}offset\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.offset) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.offset != 0 {
      try visitor.visitSingularInt32Field(value: self.offset, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_AdjustClauseBoundary, rhs: Hazkey_Commands_AdjustClauseBoundary) -> Bool {
    if lhs.offset != rhs.offset {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_PrefixComplete: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PrefixComplete"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}index\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.index) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularInt32Field(value: self.index, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_PrefixComplete, rhs: Hazkey_Commands_PrefixComplete) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_AcceptPrediction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AcceptPrediction"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}index\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.index) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularInt32Field(value: self.index, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_AcceptPrediction, rhs: Hazkey_Commands_AcceptPrediction) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_DeleteCandidateLearningData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteCandidateLearningData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}index\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.index) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularInt32Field(value: self.index, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_DeleteCandidateLearningData, rhs: Hazkey_Commands_DeleteCandidateLearningData) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_DeleteCandidateLearningDataResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteCandidateLearningDataResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}deleted_count\0\u{1}candidates\0\u{1}hiragana\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.deletedCount) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._candidates) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.hiragana) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.deletedCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.deletedCount, fieldNumber: 1)
    }
    try { if let v = self._candidates {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.hiragana.isEmpty {
      try visitor.visitSingularStringField(value: self.hiragana, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_DeleteCandidateLearningDataResult, rhs: Hazkey_Commands_DeleteCandidateLearningDataResult) -> Bool {
    if lhs.deletedCount != rhs.deletedCount {return false}
    if lhs._candidates != rhs._candidates {return false}
    if lhs.hiragana != rhs.hiragana {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_DeleteLeft: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteLeft"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_DeleteLeft, rhs: Hazkey_Commands_DeleteLeft) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_DeleteRight: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteRight"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_DeleteRight, rhs: Hazkey_Commands_DeleteRight) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_GetComposingString: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetComposingString"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}char_type\0\u{3}current_preedit\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.charType) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.currentPreedit) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.charType != .hiragana {
      try visitor.visitSingularEnumField(value: self.charType, fieldNumber: 1)
    }
    if !self.currentPreedit.isEmpty {
      try visitor.visitSingularStringField(value: self.currentPreedit, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_GetComposingString, rhs: Hazkey_Commands_GetComposingString) -> Bool {
    if lhs.charType != rhs.charType {return false}
    if lhs.currentPreedit != rhs.currentPreedit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_GetComposingString.CharType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HIRAGANA\0\u{1}KATAKANA_FULL\0\u{1}KATAKANA_HALF\0\u{1}ALPHABET_FULL\0\u{1}ALPHABET_HALF\0")
}

nonisolated extension Hazkey_Commands_GetHiraganaWithCursor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetHiraganaWithCursor"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_GetHiraganaWithCursor, rhs: Hazkey_Commands_GetHiraganaWithCursor) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_GetCandidates: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetCandidates"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_suggest\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isSuggest) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isSuggest != false {
      try visitor.visitSingularBoolField(value: self.isSuggest, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_GetCandidates, rhs: Hazkey_Commands_GetCandidates) -> Bool {
    if lhs.isSuggest != rhs.isSuggest {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_GetCurrentInputModeInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetCurrentInputModeInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_GetCurrentInputModeInfo, rhs: Hazkey_Commands_GetCurrentInputModeInfo) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_SaveLearningData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SaveLearningData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_SaveLearningData, rhs: Hazkey_Commands_SaveLearningData) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_ToggleZenzai: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ToggleZenzai"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_ToggleZenzai, rhs: Hazkey_Commands_ToggleZenzai) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_ToggleZenzaiResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ToggleZenzaiResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}enabled\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_ToggleZenzaiResult, rhs: Hazkey_Commands_ToggleZenzaiResult) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_Text: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Text"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_Text, rhs: Hazkey_Commands_Text) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_TextWithCursor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TextWithCursor"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}beforeCursosr\0\u{1}onCursor\0\u{1}afterCursor\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.beforeCursosr) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.onCursor) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.afterCursor) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.beforeCursosr.isEmpty {
      try visitor.visitSingularStringField(value: self.beforeCursosr, fieldNumber: 1)
    }
    if !self.onCursor.isEmpty {
      try visitor.visitSingularStringField(value: self.onCursor, fieldNumber: 2)
    }
    if !self.afterCursor.isEmpty {
      try visitor.visitSingularStringField(value: self.afterCursor, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_TextWithCursor, rhs: Hazkey_Commands_TextWithCursor) -> Bool {
    if lhs.beforeCursosr != rhs.beforeCursosr {return false}
    if lhs.onCursor != rhs.onCursor {return false}
    if lhs.afterCursor != rhs.afterCursor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_CandidatesResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CandidatesResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}candidates\0\u{3}live_text\0\u{3}live_text_index\0\u{3}page_size\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.candidates) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.liveText) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.liveTextIndex) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.pageSize) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.candidates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.candidates, fieldNumber: 1)
    }
    if !self.liveText.isEmpty {
      try visitor.visitSingularStringField(value: self.liveText, fieldNumber: 2)
    }
    if self.liveTextIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.liveTextIndex, fieldNumber: 3)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularInt32Field(value: self.pageSize, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_CandidatesResult, rhs: Hazkey_Commands_CandidatesResult) -> Bool {
    if lhs.candidates != rhs.candidates {return false}
    if lhs.liveText != rhs.liveText {return false}
    if lhs.liveTextIndex != rhs.liveTextIndex {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_CandidatesResult.Candidate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Commands_CandidatesResult.protoMessageName + ".Candidate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{3}sub_hiragana\0\u{3}has_learning_entry\0\u{3}is_typo_correction\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.subHiragana) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._hasLearningEntry_p) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._isTypoCorrection) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    if !self.subHiragana.isEmpty {
      try visitor.visitSingularStringField(value: self.subHiragana, fieldNumber: 2)
    }
    try { if let v = self._hasLearningEntry_p {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._isTypoCorrection {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_CandidatesResult.Candidate, rhs: Hazkey_Commands_CandidatesResult.Candidate) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.subHiragana != rhs.subHiragana {return false}
    if lhs._hasLearningEntry_p != rhs._hasLearningEntry_p {return false}
    if lhs._isTypoCorrection != rhs._isTypoCorrection {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_ClauseBoundaryResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ClauseBoundaryResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}candidates\0\u{1}hiragana\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._candidates) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.hiragana) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._candidates {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.hiragana.isEmpty {
      try visitor.visitSingularStringField(value: self.hiragana, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_ClauseBoundaryResult, rhs: Hazkey_Commands_ClauseBoundaryResult) -> Bool {
    if lhs._candidates != rhs._candidates {return false}
    if lhs.hiragana != rhs.hiragana {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_CurrentInputModeInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CurrentInputModeInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_mode\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.inputMode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.inputMode != .normal {
      try visitor.visitSingularEnumField(value: self.inputMode, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Commands_CurrentInputModeInfo, rhs: Hazkey_Commands_CurrentInputModeInfo) -> Bool {
    if lhs.inputMode != rhs.inputMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Commands_CurrentInputModeInfo.InputMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NORMAL\0\u{1}DIRECT\0")
}
