// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Hazkey_Config_FileHash: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var sha256Sum: String = String()

  var type: Hazkey_Config_FileHash.ConfigFileType = .configMain

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum ConfigFileType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case configMain // = 0
    case inputTable // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .configMain
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .configMain
      case 1: self = .inputTable
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .configMain: return 0
      case .inputTable: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Config_FileHash.ConfigFileType] = [
      .configMain,
      .inputTable,
    ]

  }

  init() {}
}

nonisolated struct Hazkey_Config_Keymap: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var isBuiltIn: Bool = false

  var filename: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_InputTable: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var isBuiltIn: Bool = false

  var filename: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_BackendDevice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var desc: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_Profile: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var serverVersion: String {
    get {_storage._serverVersion ?? String()}
    set {_uniqueStorage()._serverVersion = newValue}
  }
  /// Returns true if `serverVersion` has been explicitly set.
  var hasServerVersion: Bool {_storage._serverVersion != nil}
  /// Clears the value of `serverVersion`. Subsequent reads from it will return its default value.
  mutating func clearServerVersion() {_uniqueStorage()._serverVersion = nil}

  var profileName: String {
    get {_storage._profileName}
    set {_uniqueStorage()._profileName = newValue}
  }

  var profileID: String {
    get {_storage._profileID}
    set {_uniqueStorage()._profileID = newValue}
  }

  var useDefaultInputUiSettings: Bool {
    get {_storage._useDefaultInputUiSettings ?? false}
    set {_uniqueStorage()._useDefaultInputUiSettings = newValue}
  }
  /// Returns true if `useDefaultInputUiSettings` has been explicitly set.
  var hasUseDefaultInputUiSettings: Bool {_storage._useDefaultInputUiSettings != nil}
  /// Clears the value of `useDefaultInputUiSettings`. Subsequent reads from it will return its default value.
  mutating func clearUseDefaultInputUiSettings() {_uniqueStorage()._useDefaultInputUiSettings = nil}

  var autoConvertMode: Hazkey_Config_Profile.AutoConvertMode {
    get {_storage._autoConvertMode ?? .unspecified}
    set {_uniqueStorage()._autoConvertMode = newValue}
  }
  /// Returns true if `autoConvertMode` has been explicitly set.
  var hasAutoConvertMode: Bool {_storage._autoConvertMode != nil}
  /// Clears the value of `autoConvertMode`. Subsequent reads from it will return its default value.
  mutating func clearAutoConvertMode() {_uniqueStorage()._autoConvertMode = nil}

  var auxTextMode: Hazkey_Config_Profile.AuxTextMode {
    get {_storage._auxTextMode ?? .unspecified}
    set {_uniqueStorage()._auxTextMode = newValue}
  }
  /// Returns true if `auxTextMode` has been explicitly set.
  var hasAuxTextMode: Bool {_storage._auxTextMode != nil}
  /// Clears the value of `auxTextMode`. Subsequent reads from it will return its default value.
  mutating func clearAuxTextMode() {_uniqueStorage()._auxTextMode = nil}

  var suggestionListMode: Hazkey_Config_Profile.SuggestionListMode {
    get {_storage._suggestionListMode ?? .unspecified}
    set {_uniqueStorage()._suggestionListMode = newValue}
  }
  /// Returns true if `suggestionListMode` has been explicitly set.
  var hasSuggestionListMode: Bool {_storage._suggestionListMode != nil}
  /// Clears the value of `suggestionListMode`. Subsequent reads from it will return its default value.
  mutating func clearSuggestionListMode() {_uniqueStorage()._suggestionListMode = nil}

  var useRichSuggestion: Bool {
    get {_storage._useRichSuggestion ?? false}
    set {_uniqueStorage()._useRichSuggestion = newValue}
  }
  /// Returns true if `useRichSuggestion` has been explicitly set.
  var hasUseRichSuggestion: Bool {_storage._useRichSuggestion != nil}
  /// Clears the value of `useRichSuggestion`. Subsequent reads from it will return its default value.
  mutating func clearUseRichSuggestion() {_uniqueStorage()._useRichSuggestion = nil}

  var numSuggestions: Int32 {
    get {_storage._numSuggestions ?? 0}
    set {_uniqueStorage()._numSuggestions = newValue}
  }
  /// Returns true if `numSuggestions` has been explicitly set.
  var hasNumSuggestions: Bool {_storage._numSuggestions != nil}
  /// Clears the value of `numSuggestions`. Subsequent reads from it will return its default value.
  mutating func clearNumSuggestions() {_uniqueStorage()._numSuggestions = nil}

  var autoConvertMinChars: Int32 {
    get {_storage._autoConvertMinChars ?? 0}
    set {_uniqueStorage()._autoConvertMinChars = newValue}
  }
  /// Returns true if `autoConvertMinChars` has been explicitly set.
  var hasAutoConvertMinChars: Bool {_storage._autoConvertMinChars != nil}
  /// Clears the value of `autoConvertMinChars`. Subsequent reads from it will return its default value.
  mutating func clearAutoConvertMinChars() {_uniqueStorage()._autoConvertMinChars = nil}

  var useDefaultConversionUiSettings: Bool {
    get {_storage._useDefaultConversionUiSettings ?? false}
    set {_uniqueStorage()._useDefaultConversionUiSettings = newValue}
  }
  /// Returns true if `useDefaultConversionUiSettings` has been explicitly set.
  var hasUseDefaultConversionUiSettings: Bool {_storage._useDefaultConversionUiSettings != nil}
  /// Clears the value of `useDefaultConversionUiSettings`. Subsequent reads from it will return its default value.
  mutating func clearUseDefaultConversionUiSettings() {_uniqueStorage()._useDefaultConversionUiSettings = nil}

  var numCandidatesPerPage: Int32 {
    get {_storage._numCandidatesPerPage ?? 0}
    set {_uniqueStorage()._numCandidatesPerPage = newValue}
  }
  /// Returns true if `numCandidatesPerPage` has been explicitly set.
  var hasNumCandidatesPerPage: Bool {_storage._numCandidatesPerPage != nil}
  /// Clears the value of `numCandidatesPerPage`. Subsequent reads from it will return its default value.
  mutating func clearNumCandidatesPerPage() {_uniqueStorage()._numCandidatesPerPage = nil}

  var useRichCandidates: Bool {
    get {_storage._useRichCandidates ?? false}
    set {_uniqueStorage()._useRichCandidates = newValue}
  }
  /// Returns true if `useRichCandidates` has been explicitly set.
  var hasUseRichCandidates: Bool {_storage._useRichCandidates != nil}
  /// Clears the value of `useRichCandidates`. Subsequent reads from it will return its default value.
  mutating func clearUseRichCandidates() {_uniqueStorage()._useRichCandidates = nil}

  var useDefaultHistorySettings: Bool {
    get {_storage._useDefaultHistorySettings ?? false}
    set {_uniqueStorage()._useDefaultHistorySettings = newValue}
  }
  /// Returns true if `useDefaultHistorySettings` has been explicitly set.
  var hasUseDefaultHistorySettings: Bool {_storage._useDefaultHistorySettings != nil}
  /// Clears the value of `useDefaultHistorySettings`. Subsequent reads from it will return its default value.
  mutating func clearUseDefaultHistorySettings() {_uniqueStorage()._useDefaultHistorySettings = nil}

  var useProfileIndependentHistory: Bool {
    get {_storage._useProfileIndependentHistory ?? false}
    set {_uniqueStorage()._useProfileIndependentHistory = newValue}
  }
  /// Returns true if `useProfileIndependentHistory` has been explicitly set.
  var hasUseProfileIndependentHistory: Bool {_storage._useProfileIndependentHistory != nil}
  /// Clears the value of `useProfileIndependentHistory`. Subsequent reads from it will return its default value.
  mutating func clearUseProfileIndependentHistory() {_uniqueStorage()._useProfileIndependentHistory = nil}

  var useInputHistory: Bool {
    get {_storage._useInputHistory ?? false}
    set {_uniqueStorage()._useInputHistory = newValue}
  }
  /// Returns true if `useInputHistory` has been explicitly set.
  var hasUseInputHistory: Bool {_storage._useInputHistory != nil}
  /// Clears the value of `useInputHistory`. Subsequent reads from it will return its default value.
  mutating func clearUseInputHistory() {_uniqueStorage()._useInputHistory = nil}

  var stopStoreNewHistory: Bool {
    get {_storage._stopStoreNewHistory ?? false}
    set {_uniqueStorage()._stopStoreNewHistory = newValue}
  }
  /// Returns true if `stopStoreNewHistory` has been explicitly set.
  var hasStopStoreNewHistory: Bool {_storage._stopStoreNewHistory != nil}
  /// Clears the value of `stopStoreNewHistory`. Subsequent reads from it will return its default value.
  mutating func clearStopStoreNewHistory() {_uniqueStorage()._stopStoreNewHistory = nil}

  var useDefaultSpecialConversionSettings: Bool {
    get {_storage._useDefaultSpecialConversionSettings ?? false}
    set {_uniqueStorage()._useDefaultSpecialConversionSettings = newValue}
  }
  /// Returns true if `useDefaultSpecialConversionSettings` has been explicitly set.
  var hasUseDefaultSpecialConversionSettings: Bool {_storage._useDefaultSpecialConversionSettings != nil}
  /// Clears the value of `useDefaultSpecialConversionSettings`. Subsequent reads from it will return its default value.
  mutating func clearUseDefaultSpecialConversionSettings() {_uniqueStorage()._useDefaultSpecialConversionSettings = nil}

  var specialConversionMode: Hazkey_Config_Profile.SpecialConversionMode {
    get {_storage._specialConversionMode ?? Hazkey_Config_Profile.SpecialConversionMode()}
    set {_uniqueStorage()._specialConversionMode = newValue}
  }
  /// Returns true if `specialConversionMode` has been explicitly set.
  var hasSpecialConversionMode: Bool {_storage._specialConversionMode != nil}
  /// Clears the value of `specialConversionMode`. Subsequent reads from it will return its default value.
  mutating func clearSpecialConversionMode() {_uniqueStorage()._specialConversionMode = nil}

  var useDefaultKeymapSettings: Bool {
    get {_storage._useDefaultKeymapSettings ?? false}
    set {_uniqueStorage()._useDefaultKeymapSettings = newValue}
  }
  /// Returns true if `useDefaultKeymapSettings` has been explicitly set.
  var hasUseDefaultKeymapSettings: Bool {_storage._useDefaultKeymapSettings != nil}
  /// Clears the value of `useDefaultKeymapSettings`. Subsequent reads from it will return its default value.
  mutating func clearUseDefaultKeymapSettings() {_uniqueStorage()._useDefaultKeymapSettings = nil}

  var enabledKeymaps: [Hazkey_Config_Profile.EnabledKeymap] {
    get {_storage._enabledKeymaps}
    set {_uniqueStorage()._enabledKeymaps = newValue}
  }

  var useDefaultTableSettings: Bool {
    get {_storage._useDefaultTableSettings ?? false}
    set {_uniqueStorage()._useDefaultTableSettings = newValue}
  }
  /// Returns true if `useDefaultTableSettings` has been explicitly set.
  var hasUseDefaultTableSettings: Bool {_storage._useDefaultTableSettings != nil}
  /// Clears the value of `useDefaultTableSettings`. Subsequent reads from it will return its default value.
  mutating func clearUseDefaultTableSettings() {_uniqueStorage()._useDefaultTableSettings = nil}

  var enabledTables: [Hazkey_Config_Profile.EnabledInputTable] {
    get {_storage._enabledTables}
    set {_uniqueStorage()._enabledTables = newValue}
  }

  var submodeEntryPointChars: String {
    get {_storage._submodeEntryPointChars ?? String()}
    set {_uniqueStorage()._submodeEntryPointChars = newValue}
  }
  /// Returns true if `submodeEntryPointChars` has been explicitly set.
  var hasSubmodeEntryPointChars: Bool {_storage._submodeEntryPointChars != nil}
  /// Clears the value of `submodeEntryPointChars`. Subsequent reads from it will return its default value.
  mutating func clearSubmodeEntryPointChars() {_uniqueStorage()._submodeEntryPointChars = nil}

  var autoConvertHotkey: String {
    get {_storage._autoConvertHotkey ?? String()}
    set {_uniqueStorage()._autoConvertHotkey = newValue}
  }
  /// Returns true if `autoConvertHotkey` has been explicitly set.
  var hasAutoConvertHotkey: Bool {_storage._autoConvertHotkey != nil}
  /// Clears the value of `autoConvertHotkey`. Subsequent reads from it will return its default value.
  mutating func clearAutoConvertHotkey() {_uniqueStorage()._autoConvertHotkey = nil}

  var useUserDictionary: Bool {
    get {_storage._useUserDictionary ?? false}
    set {_uniqueStorage()._useUserDictionary = newValue}
  }
  /// Returns true if `useUserDictionary` has been explicitly set.
  var hasUseUserDictionary: Bool {_storage._useUserDictionary != nil}
  /// Clears the value of `useUserDictionary`. Subsequent reads from it will return its default value.
  mutating func clearUseUserDictionary() {_uniqueStorage()._useUserDictionary = nil}

  var useDefaultZenzaiSettings: Bool {
    get {_storage._useDefaultZenzaiSettings ?? false}
    set {_uniqueStorage()._useDefaultZenzaiSettings = newValue}
  }
  /// Returns true if `useDefaultZenzaiSettings` has been explicitly set.
  var hasUseDefaultZenzaiSettings: Bool {_storage._useDefaultZenzaiSettings != nil}
  /// Clears the value of `useDefaultZenzaiSettings`. Subsequent reads from it will return its default value.
  mutating func clearUseDefaultZenzaiSettings() {_uniqueStorage()._useDefaultZenzaiSettings = nil}

  var zenzaiEnable: Bool {
    get {_storage._zenzaiEnable ?? false}
    set {_uniqueStorage()._zenzaiEnable = newValue}
  }
  /// Returns true if `zenzaiEnable` has been explicitly set.
  var hasZenzaiEnable: Bool {_storage._zenzaiEnable != nil}
  /// Clears the value of `zenzaiEnable`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiEnable() {_uniqueStorage()._zenzaiEnable = nil}

  var zenzaiInferLimit: Int32 {
    get {_storage._zenzaiInferLimit ?? 0}
    set {_uniqueStorage()._zenzaiInferLimit = newValue}
  }
  /// Returns true if `zenzaiInferLimit` has been explicitly set.
  var hasZenzaiInferLimit: Bool {_storage._zenzaiInferLimit != nil}
  /// Clears the value of `zenzaiInferLimit`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiInferLimit() {_uniqueStorage()._zenzaiInferLimit = nil}

  var zenzaiContextualMode: Bool {
    get {_storage._zenzaiContextualMode ?? false}
    set {_uniqueStorage()._zenzaiContextualMode = newValue}
  }
  /// Returns true if `zenzaiContextualMode` has been explicitly set.
  var hasZenzaiContextualMode: Bool {_storage._zenzaiContextualMode != nil}
  /// Clears the value of `zenzaiContextualMode`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiContextualMode() {_uniqueStorage()._zenzaiContextualMode = nil}

  var useZenzaiCustomWeight: Bool {
    get {_storage._useZenzaiCustomWeight ?? false}
    set {_uniqueStorage()._useZenzaiCustomWeight = newValue}
  }
  /// Returns true if `useZenzaiCustomWeight` has been explicitly set.
  var hasUseZenzaiCustomWeight: Bool {_storage._useZenzaiCustomWeight != nil}
  /// Clears the value of `useZenzaiCustomWeight`. Subsequent reads from it will return its default value.
  mutating func clearUseZenzaiCustomWeight() {_uniqueStorage()._useZenzaiCustomWeight = nil}

  var zenzaiWeightPath: String {
    get {_storage._zenzaiWeightPath ?? String()}
    set {_uniqueStorage()._zenzaiWeightPath = newValue}
  }
  /// Returns true if `zenzaiWeightPath` has been explicitly set.
  var hasZenzaiWeightPath: Bool {_storage._zenzaiWeightPath != nil}
  /// Clears the value of `zenzaiWeightPath`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiWeightPath() {_uniqueStorage()._zenzaiWeightPath = nil}

  var zenzaiBackendDeviceName: String {
    get {_storage._zenzaiBackendDeviceName ?? String()}
    set {_uniqueStorage()._zenzaiBackendDeviceName = newValue}
  }
  /// Returns true if `zenzaiBackendDeviceName` has been explicitly set.
  var hasZenzaiBackendDeviceName: Bool {_storage._zenzaiBackendDeviceName != nil}
  /// Clears the value of `zenzaiBackendDeviceName`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiBackendDeviceName() {_uniqueStorage()._zenzaiBackendDeviceName = nil}

  var zenzaiProfile: String {
    get {_storage._zenzaiProfile ?? String()}
    set {_uniqueStorage()._zenzaiProfile = newValue}
  }
  /// Returns true if `zenzaiProfile` has been explicitly set.
  var hasZenzaiProfile: Bool {_storage._zenzaiProfile != nil}
  /// Clears the value of `zenzaiProfile`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiProfile() {_uniqueStorage()._zenzaiProfile = nil}

  var zenzaiTopic: String {
    get {_storage._zenzaiTopic ?? String()}
    set {_uniqueStorage()._zenzaiTopic = newValue}
  }
  /// Returns true if `zenzaiTopic` has been explicitly set.
  var hasZenzaiTopic: Bool {_storage._zenzaiTopic != nil}
  /// Clears the value of `zenzaiTopic`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiTopic() {_uniqueStorage()._zenzaiTopic = nil}

  var zenzaiStyle: String {
    get {_storage._zenzaiStyle ?? String()}
    set {_uniqueStorage()._zenzaiStyle = newValue}
  }
  /// Returns true if `zenzaiStyle` has been explicitly set.
  var hasZenzaiStyle: Bool {_storage._zenzaiStyle != nil}
  /// Clears the value of `zenzaiStyle`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiStyle() {_uniqueStorage()._zenzaiStyle = nil}

  var zenzaiPreference: String {
    get {_storage._zenzaiPreference ?? String()}
    set {_uniqueStorage()._zenzaiPreference = newValue}
  }
  /// Returns true if `zenzaiPreference` has been explicitly set.
  var hasZenzaiPreference: Bool {_storage._zenzaiPreference != nil}
  /// Clears the value of `zenzaiPreference`. Subsequent reads from it will return its default value.
  mutating func clearZenzaiPreference() {_uniqueStorage()._zenzaiPreference = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum AutoConvertMode: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case autoConvertDisabled // = 1
    case autoConvertAlways // = 2
    case autoConvertForMultipleChars // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .autoConvertDisabled
      case 2: self = .autoConvertAlways
      case 3: self = .autoConvertForMultipleChars
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .autoConvertDisabled: return 1
      case .autoConvertAlways: return 2
      case .autoConvertForMultipleChars: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Config_Profile.AutoConvertMode] = [
      .unspecified,
      .autoConvertDisabled,
      .autoConvertAlways,
      .autoConvertForMultipleChars,
    ]

  }

  nonisolated enum AuxTextMode: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case auxTextDisabled // = 1
    case auxTextShowAlways // = 2
    case auxTextShowWhenCursorNotAtEnd // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .auxTextDisabled
      case 2: self = .auxTextShowAlways
      case 3: self = .auxTextShowWhenCursorNotAtEnd
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .auxTextDisabled: return 1
      case .auxTextShowAlways: return 2
      case .auxTextShowWhenCursorNotAtEnd: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Config_Profile.AuxTextMode] = [
      .unspecified,
      .auxTextDisabled,
      .auxTextShowAlways,
      .auxTextShowWhenCursorNotAtEnd,
    ]

  }

  nonisolated enum SuggestionListMode: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case suggestionListDisabled // = 1
    case suggestionListShowNormalResults // = 2
    case suggestionListShowPredictiveResults // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .suggestionListDisabled
      case 2: self = .suggestionListShowNormalResults
      case 3: self = .suggestionListShowPredictiveResults
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .suggestionListDisabled: return 1
      case .suggestionListShowNormalResults: return 2
      case .suggestionListShowPredictiveResults: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Hazkey_Config_Profile.SuggestionListMode] = [
      .unspecified,
      .suggestionListDisabled,
      .suggestionListShowNormalResults,
      .suggestionListShowPredictiveResults,
    ]

  }

  nonisolated struct SpecialConversionMode: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var commaSeparatedNumber: Bool {
      get {_commaSeparatedNumber ?? false}
      set {_commaSeparatedNumber = newValue}
    }
    /// Returns true if `commaSeparatedNumber` has been explicitly set.
    var hasCommaSeparatedNumber: Bool {self._commaSeparatedNumber != nil}
    /// Clears the value of `commaSeparatedNumber`. Subsequent reads from it will return its default value.
    mutating func clearCommaSeparatedNumber() {self._commaSeparatedNumber = nil}

    var mailDomain: Bool {
      get {_mailDomain ?? false}
      set {_mailDomain = newValue}
    }
    /// Returns true if `mailDomain` has been explicitly set.
    var hasMailDomain: Bool {self._mailDomain != nil}
    /// Clears the value of `mailDomain`. Subsequent reads from it will return its default value.
    mutating func clearMailDomain() {self._mailDomain = nil}

    var calendar: Bool {
      get {_calendar ?? false}
      set {_calendar = newValue}
    }
    /// Returns true if `calendar` has been explicitly set.
    var hasCalendar: Bool {self._calendar != nil}
    /// Clears the value of `calendar`. Subsequent reads from it will return its default value.
    mutating func clearCalendar() {self._calendar = nil}

    var time: Bool {
      get {_time ?? false}
      set {_time = newValue}
    }
    /// Returns true if `time` has been explicitly set.
    var hasTime: Bool {self._time != nil}
    /// Clears the value of `time`. Subsequent reads from it will return its default value.
    mutating func clearTime() {self._time = nil}

    var romanTypography: Bool {
      get {_romanTypography ?? false}
      set {_romanTypography = newValue}
    }
    /// Returns true if `romanTypography` has been explicitly set.
    var hasRomanTypography: Bool {self._romanTypography != nil}
    /// Clears the value of `romanTypography`. Subsequent reads from it will return its default value.
    mutating func clearRomanTypography() {self._romanTypography = nil}

    var unicodeCodepoint: Bool {
      get {_unicodeCodepoint ?? false}
      set {_unicodeCodepoint = newValue}
    }
    /// Returns true if `unicodeCodepoint` has been explicitly set.
    var hasUnicodeCodepoint: Bool {self._unicodeCodepoint != nil}
    /// Clears the value of `unicodeCodepoint`. Subsequent reads from it will return its default value.
    mutating func clearUnicodeCodepoint() {self._unicodeCodepoint = nil}

    var hazkeyVersion: Bool {
      get {_hazkeyVersion ?? false}
      set {_hazkeyVersion = newValue}
    }
    /// Returns true if `hazkeyVersion` has been explicitly set.
    var hasHazkeyVersion: Bool {self._hazkeyVersion != nil}
    /// Clears the value of `hazkeyVersion`. Subsequent reads from it will return its default value.
    mutating func clearHazkeyVersion() {self._hazkeyVersion = nil}

    /// [community] Relative-date candidates (きょう → 今日 + 2026年8月11日 + ...).
    /// When enabled, formatted date strings are appended after the kanji
    /// representation of recognized trigger words.
    var relativeDate: Bool {
      get {_relativeDate ?? false}
      set {_relativeDate = newValue}
    }
    /// Returns true if `relativeDate` has been explicitly set.
    var hasRelativeDate: Bool {self._relativeDate != nil}
    /// Clears the value of `relativeDate`. Subsequent reads from it will return its default value.
    mutating func clearRelativeDate() {self._relativeDate = nil}

    var halfwidthKatakana: Bool {
      get {_halfwidthKatakana ?? false}
      set {_halfwidthKatakana = newValue}
    }
    /// Returns true if `halfwidthKatakana` has been explicitly set.
    var hasHalfwidthKatakana: Bool {self._halfwidthKatakana != nil}
    /// Clears the value of `halfwidthKatakana`. Subsequent reads from it will return its default value.
    mutating func clearHalfwidthKatakana() {self._halfwidthKatakana = nil}

    var extendedEmoji: Bool {
      get {_extendedEmoji ?? false}
      set {_extendedEmoji = newValue}
    }
    /// Returns true if `extendedEmoji` has been explicitly set.
    var hasExtendedEmoji: Bool {self._extendedEmoji != nil}
    /// Clears the value of `extendedEmoji`. Subsequent reads from it will return its default value.
    mutating func clearExtendedEmoji() {self._extendedEmoji = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _commaSeparatedNumber: Bool? = nil
    fileprivate var _mailDomain: Bool? = nil
    fileprivate var _calendar: Bool? = nil
    fileprivate var _time: Bool? = nil
    fileprivate var _romanTypography: Bool? = nil
    fileprivate var _unicodeCodepoint: Bool? = nil
    fileprivate var _hazkeyVersion: Bool? = nil
    fileprivate var _relativeDate: Bool? = nil
    fileprivate var _halfwidthKatakana: Bool? = nil
    fileprivate var _extendedEmoji: Bool? = nil
  }

  nonisolated struct EnabledKeymap: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var name: String {
      get {_name ?? String()}
      set {_name = newValue}
    }
    /// Returns true if `name` has been explicitly set.
    var hasName: Bool {self._name != nil}
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    mutating func clearName() {self._name = nil}

    var isBuiltIn: Bool {
      get {_isBuiltIn ?? false}
      set {_isBuiltIn = newValue}
    }
    /// Returns true if `isBuiltIn` has been explicitly set.
    var hasIsBuiltIn: Bool {self._isBuiltIn != nil}
    /// Clears the value of `isBuiltIn`. Subsequent reads from it will return its default value.
    mutating func clearIsBuiltIn() {self._isBuiltIn = nil}

    var filename: String {
      get {_filename ?? String()}
      set {_filename = newValue}
    }
    /// Returns true if `filename` has been explicitly set.
    var hasFilename: Bool {self._filename != nil}
    /// Clears the value of `filename`. Subsequent reads from it will return its default value.
    mutating func clearFilename() {self._filename = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _name: String? = nil
    fileprivate var _isBuiltIn: Bool? = nil
    fileprivate var _filename: String? = nil
  }

  nonisolated struct EnabledInputTable: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var name: String {
      get {_name ?? String()}
      set {_name = newValue}
    }
    /// Returns true if `name` has been explicitly set.
    var hasName: Bool {self._name != nil}
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    mutating func clearName() {self._name = nil}

    var isBuiltIn: Bool {
      get {_isBuiltIn ?? false}
      set {_isBuiltIn = newValue}
    }
    /// Returns true if `isBuiltIn` has been explicitly set.
    var hasIsBuiltIn: Bool {self._isBuiltIn != nil}
    /// Clears the value of `isBuiltIn`. Subsequent reads from it will return its default value.
    mutating func clearIsBuiltIn() {self._isBuiltIn = nil}

    var filename: String {
      get {_filename ?? String()}
      set {_filename = newValue}
    }
    /// Returns true if `filename` has been explicitly set.
    var hasFilename: Bool {self._filename != nil}
    /// Clears the value of `filename`. Subsequent reads from it will return its default value.
    mutating func clearFilename() {self._filename = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _name: String? = nil
    fileprivate var _isBuiltIn: Bool? = nil
    fileprivate var _filename: String? = nil
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

nonisolated struct Hazkey_Config_GetConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_SetConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileHashes: [Hazkey_Config_FileHash] = []

  var profiles: [Hazkey_Config_Profile] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_GetDefaultProfile: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_ClearAllHistory: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var profileID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_ReloadZenzaiModel: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_CurrentConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileHashes: [Hazkey_Config_FileHash] = []

  var profiles: [Hazkey_Config_Profile] = []

  var availableKeymaps: [Hazkey_Config_Keymap] = []

  var availableTables: [Hazkey_Config_InputTable] = []

  var availableZenzaiBackendDevices: [Hazkey_Config_BackendDevice] = []

  var zenzaiModelAvailable: Bool = false

  var zenzaiModelPath: String = String()

  var xdgConfigHomePath: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_GetLearningHistory: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var profileID: String = String()

  /// Partial match on reading or word is applied before pagination.
  var query: String = String()

  var offset: UInt32 = 0

  /// The server clamps this value to at most 200.
  var limit: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_LearningEntryKey: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var reading: String = String()

  var word: String = String()

  var lcid: UInt32 = 0

  var rcid: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_DeleteLearningEntries: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var profileID: String = String()

  var entries: [Hazkey_Config_LearningEntryKey] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_LearningHistoryEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var reading: String = String()

  var word: String = String()

  var lcid: UInt32 = 0

  var rcid: UInt32 = 0

  var count: UInt32 = 0

  /// Days since the Unix epoch.
  var lastUsedUnixDay: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_GetLearningHistoryResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var entries: [Hazkey_Config_LearningHistoryEntry] = []

  var totalCount: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Hazkey_Config_DeleteLearningEntriesResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var deletedCount: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "hazkey.config"

nonisolated extension Hazkey_Config_FileHash: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileHash"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}sha256sum\0\u{1}type\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sha256Sum) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.sha256Sum.isEmpty {
      try visitor.visitSingularStringField(value: self.sha256Sum, fieldNumber: 2)
    }
    if self.type != .configMain {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_FileHash, rhs: Hazkey_Config_FileHash) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.sha256Sum != rhs.sha256Sum {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_FileHash.ConfigFileType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CONFIG_MAIN\0\u{1}INPUT_TABLE\0")
}

nonisolated extension Hazkey_Config_Keymap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Keymap"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}is_built_in\0\u{1}filename\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isBuiltIn) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.filename) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.isBuiltIn != false {
      try visitor.visitSingularBoolField(value: self.isBuiltIn, fieldNumber: 2)
    }
    if !self.filename.isEmpty {
      try visitor.visitSingularStringField(value: self.filename, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_Keymap, rhs: Hazkey_Config_Keymap) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.isBuiltIn != rhs.isBuiltIn {return false}
    if lhs.filename != rhs.filename {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_InputTable: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InputTable"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}is_built_in\0\u{1}filename\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isBuiltIn) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.filename) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.isBuiltIn != false {
      try visitor.visitSingularBoolField(value: self.isBuiltIn, fieldNumber: 2)
    }
    if !self.filename.isEmpty {
      try visitor.visitSingularStringField(value: self.filename, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_InputTable, rhs: Hazkey_Config_InputTable) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.isBuiltIn != rhs.isBuiltIn {return false}
    if lhs.filename != rhs.filename {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_BackendDevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BackendDevice"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}desc\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.desc) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.desc.isEmpty {
      try visitor.visitSingularStringField(value: self.desc, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_BackendDevice, rhs: Hazkey_Config_BackendDevice) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.desc != rhs.desc {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_Profile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Profile"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{4}server_version\0\u{3}profile_name\0\u{3}profile_id\0\u{4}\u{4}use_default_input_ui_settings\0\u{3}auto_convert_mode\0\u{3}aux_text_mode\0\u{3}suggestion_list_mode\0\u{3}use_rich_suggestion\0\u{3}num_suggestions\0\u{3}auto_convert_min_chars\0\u{4}\u{4}use_default_conversion_ui_settings\0\u{3}num_candidates_per_page\0\u{3}use_rich_candidates\0\u{3}stop_store_new_history\0\u{4}\u{7}use_default_history_settings\0\u{3}use_profile_independent_history\0\u{3}use_input_history\0\u{4}\u{8}use_default_special_conversion_settings\0\u{3}special_conversion_mode\0\u{4}\u{9}use_default_keymap_settings\0\u{3}enabled_keymaps\0\u{4}\u{4}use_default_table_settings\0\u{3}enabled_tables\0\u{4}\u{4}submode_entry_point_chars\0\u{3}auto_convert_hotkey\0\u{4}\u{9}use_user_dictionary\0\u{4}\u{1e}use_default_zenzai_settings\0\u{3}zenzai_enable\0\u{3}zenzai_infer_limit\0\u{3}zenzai_contextual_mode\0\u{4}\u{2}use_zenzai_custom_weight\0\u{3}zenzai_weight_path\0\u{3}zenzai_backend_device_name\0\u{4}\u{d}zenzai_profile\0\u{3}zenzai_topic\0\u{3}zenzai_style\0\u{3}zenzai_preference\0")

  fileprivate class _StorageClass {
    var _serverVersion: String? = nil
    var _profileName: String = String()
    var _profileID: String = String()
    var _useDefaultInputUiSettings: Bool? = nil
    var _autoConvertMode: Hazkey_Config_Profile.AutoConvertMode? = nil
    var _auxTextMode: Hazkey_Config_Profile.AuxTextMode? = nil
    var _suggestionListMode: Hazkey_Config_Profile.SuggestionListMode? = nil
    var _useRichSuggestion: Bool? = nil
    var _numSuggestions: Int32? = nil
    var _autoConvertMinChars: Int32? = nil
    var _useDefaultConversionUiSettings: Bool? = nil
    var _numCandidatesPerPage: Int32? = nil
    var _useRichCandidates: Bool? = nil
    var _useDefaultHistorySettings: Bool? = nil
    var _useProfileIndependentHistory: Bool? = nil
    var _useInputHistory: Bool? = nil
    var _stopStoreNewHistory: Bool? = nil
    var _useDefaultSpecialConversionSettings: Bool? = nil
    var _specialConversionMode: Hazkey_Config_Profile.SpecialConversionMode? = nil
    var _useDefaultKeymapSettings: Bool? = nil
    var _enabledKeymaps: [Hazkey_Config_Profile.EnabledKeymap] = []
    var _useDefaultTableSettings: Bool? = nil
    var _enabledTables: [Hazkey_Config_Profile.EnabledInputTable] = []
    var _submodeEntryPointChars: String? = nil
    var _autoConvertHotkey: String? = nil
    var _useUserDictionary: Bool? = nil
    var _useDefaultZenzaiSettings: Bool? = nil
    var _zenzaiEnable: Bool? = nil
    var _zenzaiInferLimit: Int32? = nil
    var _zenzaiContextualMode: Bool? = nil
    var _useZenzaiCustomWeight: Bool? = nil
    var _zenzaiWeightPath: String? = nil
    var _zenzaiBackendDeviceName: String? = nil
    var _zenzaiProfile: String? = nil
    var _zenzaiTopic: String? = nil
    var _zenzaiStyle: String? = nil
    var _zenzaiPreference: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _serverVersion = source._serverVersion
      _profileName = source._profileName
      _profileID = source._profileID
      _useDefaultInputUiSettings = source._useDefaultInputUiSettings
      _autoConvertMode = source._autoConvertMode
      _auxTextMode = source._auxTextMode
      _suggestionListMode = source._suggestionListMode
      _useRichSuggestion = source._useRichSuggestion
      _numSuggestions = source._numSuggestions
      _autoConvertMinChars = source._autoConvertMinChars
      _useDefaultConversionUiSettings = source._useDefaultConversionUiSettings
      _numCandidatesPerPage = source._numCandidatesPerPage
      _useRichCandidates = source._useRichCandidates
      _useDefaultHistorySettings = source._useDefaultHistorySettings
      _useProfileIndependentHistory = source._useProfileIndependentHistory
      _useInputHistory = source._useInputHistory
      _stopStoreNewHistory = source._stopStoreNewHistory
      _useDefaultSpecialConversionSettings = source._useDefaultSpecialConversionSettings
      _specialConversionMode = source._specialConversionMode
      _useDefaultKeymapSettings = source._useDefaultKeymapSettings
      _enabledKeymaps = source._enabledKeymaps
      _useDefaultTableSettings = source._useDefaultTableSettings
      _enabledTables = source._enabledTables
      _submodeEntryPointChars = source._submodeEntryPointChars
      _autoConvertHotkey = source._autoConvertHotkey
      _useUserDictionary = source._useUserDictionary
      _useDefaultZenzaiSettings = source._useDefaultZenzaiSettings
      _zenzaiEnable = source._zenzaiEnable
      _zenzaiInferLimit = source._zenzaiInferLimit
      _zenzaiContextualMode = source._zenzaiContextualMode
      _useZenzaiCustomWeight = source._useZenzaiCustomWeight
      _zenzaiWeightPath = source._zenzaiWeightPath
      _zenzaiBackendDeviceName = source._zenzaiBackendDeviceName
      _zenzaiProfile = source._zenzaiProfile
      _zenzaiTopic = source._zenzaiTopic
      _zenzaiStyle = source._zenzaiStyle
      _zenzaiPreference = source._zenzaiPreference
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._serverVersion) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._profileName) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._profileID) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._useDefaultInputUiSettings) }()
        case 11: try { try decoder.decodeSingularEnumField(value: &_storage._autoConvertMode) }()
        case 12: try { try decoder.decodeSingularEnumField(value: &_storage._auxTextMode) }()
        case 13: try { try decoder.decodeSingularEnumField(value: &_storage._suggestionListMode) }()
        case 14: try { try decoder.decodeSingularBoolField(value: &_storage._useRichSuggestion) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._numSuggestions) }()
        case 16: try { try decoder.decodeSingularInt32Field(value: &_storage._autoConvertMinChars) }()
        case 20: try { try decoder.decodeSingularBoolField(value: &_storage._useDefaultConversionUiSettings) }()
        case 21: try { try decoder.decodeSingularInt32Field(value: &_storage._numCandidatesPerPage) }()
        case 22: try { try decoder.decodeSingularBoolField(value: &_storage._useRichCandidates) }()
        case 23: try { try decoder.decodeSingularBoolField(value: &_storage._stopStoreNewHistory) }()
        case 30: try { try decoder.decodeSingularBoolField(value: &_storage._useDefaultHistorySettings) }()
        case 31: try { try decoder.decodeSingularBoolField(value: &_storage._useProfileIndependentHistory) }()
        case 32: try { try decoder.decodeSingularBoolField(value: &_storage._useInputHistory) }()
        case 40: try { try decoder.decodeSingularBoolField(value: &_storage._useDefaultSpecialConversionSettings) }()
        case 41: try { try decoder.decodeSingularMessageField(value: &_storage._specialConversionMode) }()
        case 50: try { try decoder.decodeSingularBoolField(value: &_storage._useDefaultKeymapSettings) }()
        case 51: try { try decoder.decodeRepeatedMessageField(value: &_storage._enabledKeymaps) }()
        case 55: try { try decoder.decodeSingularBoolField(value: &_storage._useDefaultTableSettings) }()
        case 56: try { try decoder.decodeRepeatedMessageField(value: &_storage._enabledTables) }()
        case 60: try { try decoder.decodeSingularStringField(value: &_storage._submodeEntryPointChars) }()
        case 61: try { try decoder.decodeSingularStringField(value: &_storage._autoConvertHotkey) }()
        case 70: try { try decoder.decodeSingularBoolField(value: &_storage._useUserDictionary) }()
        case 100: try { try decoder.decodeSingularBoolField(value: &_storage._useDefaultZenzaiSettings) }()
        case 101: try { try decoder.decodeSingularBoolField(value: &_storage._zenzaiEnable) }()
        case 102: try { try decoder.decodeSingularInt32Field(value: &_storage._zenzaiInferLimit) }()
        case 103: try { try decoder.decodeSingularBoolField(value: &_storage._zenzaiContextualMode) }()
        case 105: try { try decoder.decodeSingularBoolField(value: &_storage._useZenzaiCustomWeight) }()
        case 106: try { try decoder.decodeSingularStringField(value: &_storage._zenzaiWeightPath) }()
        case 107: try { try decoder.decodeSingularStringField(value: &_storage._zenzaiBackendDeviceName) }()
        case 120: try { try decoder.decodeSingularStringField(value: &_storage._zenzaiProfile) }()
        case 121: try { try decoder.decodeSingularStringField(value: &_storage._zenzaiTopic) }()
        case 122: try { try decoder.decodeSingularStringField(value: &_storage._zenzaiStyle) }()
        case 123: try { try decoder.decodeSingularStringField(value: &_storage._zenzaiPreference) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._serverVersion {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      if !_storage._profileName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._profileName, fieldNumber: 5)
      }
      if !_storage._profileID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._profileID, fieldNumber: 6)
      }
      try { if let v = _storage._useDefaultInputUiSettings {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._autoConvertMode {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._auxTextMode {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._suggestionListMode {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._useRichSuggestion {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._numSuggestions {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 15)
      } }()
      try { if let v = _storage._autoConvertMinChars {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 16)
      } }()
      try { if let v = _storage._useDefaultConversionUiSettings {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 20)
      } }()
      try { if let v = _storage._numCandidatesPerPage {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 21)
      } }()
      try { if let v = _storage._useRichCandidates {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 22)
      } }()
      try { if let v = _storage._stopStoreNewHistory {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 23)
      } }()
      try { if let v = _storage._useDefaultHistorySettings {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 30)
      } }()
      try { if let v = _storage._useProfileIndependentHistory {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 31)
      } }()
      try { if let v = _storage._useInputHistory {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 32)
      } }()
      try { if let v = _storage._useDefaultSpecialConversionSettings {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 40)
      } }()
      try { if let v = _storage._specialConversionMode {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 41)
      } }()
      try { if let v = _storage._useDefaultKeymapSettings {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 50)
      } }()
      if !_storage._enabledKeymaps.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._enabledKeymaps, fieldNumber: 51)
      }
      try { if let v = _storage._useDefaultTableSettings {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 55)
      } }()
      if !_storage._enabledTables.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._enabledTables, fieldNumber: 56)
      }
      try { if let v = _storage._submodeEntryPointChars {
        try visitor.visitSingularStringField(value: v, fieldNumber: 60)
      } }()
      try { if let v = _storage._autoConvertHotkey {
        try visitor.visitSingularStringField(value: v, fieldNumber: 61)
      } }()
      try { if let v = _storage._useUserDictionary {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 70)
      } }()
      try { if let v = _storage._useDefaultZenzaiSettings {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 100)
      } }()
      try { if let v = _storage._zenzaiEnable {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 101)
      } }()
      try { if let v = _storage._zenzaiInferLimit {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 102)
      } }()
      try { if let v = _storage._zenzaiContextualMode {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 103)
      } }()
      try { if let v = _storage._useZenzaiCustomWeight {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 105)
      } }()
      try { if let v = _storage._zenzaiWeightPath {
        try visitor.visitSingularStringField(value: v, fieldNumber: 106)
      } }()
      try { if let v = _storage._zenzaiBackendDeviceName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 107)
      } }()
      try { if let v = _storage._zenzaiProfile {
        try visitor.visitSingularStringField(value: v, fieldNumber: 120)
      } }()
      try { if let v = _storage._zenzaiTopic {
        try visitor.visitSingularStringField(value: v, fieldNumber: 121)
      } }()
      try { if let v = _storage._zenzaiStyle {
        try visitor.visitSingularStringField(value: v, fieldNumber: 122)
      } }()
      try { if let v = _storage._zenzaiPreference {
        try visitor.visitSingularStringField(value: v, fieldNumber: 123)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_Profile, rhs: Hazkey_Config_Profile) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._serverVersion != rhs_storage._serverVersion {return false}
        if _storage._profileName != rhs_storage._profileName {return false}
        if _storage._profileID != rhs_storage._profileID {return false}
        if _storage._useDefaultInputUiSettings != rhs_storage._useDefaultInputUiSettings {return false}
        if _storage._autoConvertMode != rhs_storage._autoConvertMode {return false}
        if _storage._auxTextMode != rhs_storage._auxTextMode {return false}
        if _storage._suggestionListMode != rhs_storage._suggestionListMode {return false}
        if _storage._useRichSuggestion != rhs_storage._useRichSuggestion {return false}
        if _storage._numSuggestions != rhs_storage._numSuggestions {return false}
        if _storage._autoConvertMinChars != rhs_storage._autoConvertMinChars {return false}
        if _storage._useDefaultConversionUiSettings != rhs_storage._useDefaultConversionUiSettings {return false}
        if _storage._numCandidatesPerPage != rhs_storage._numCandidatesPerPage {return false}
        if _storage._useRichCandidates != rhs_storage._useRichCandidates {return false}
        if _storage._useDefaultHistorySettings != rhs_storage._useDefaultHistorySettings {return false}
        if _storage._useProfileIndependentHistory != rhs_storage._useProfileIndependentHistory {return false}
        if _storage._useInputHistory != rhs_storage._useInputHistory {return false}
        if _storage._stopStoreNewHistory != rhs_storage._stopStoreNewHistory {return false}
        if _storage._useDefaultSpecialConversionSettings != rhs_storage._useDefaultSpecialConversionSettings {return false}
        if _storage._specialConversionMode != rhs_storage._specialConversionMode {return false}
        if _storage._useDefaultKeymapSettings != rhs_storage._useDefaultKeymapSettings {return false}
        if _storage._enabledKeymaps != rhs_storage._enabledKeymaps {return false}
        if _storage._useDefaultTableSettings != rhs_storage._useDefaultTableSettings {return false}
        if _storage._enabledTables != rhs_storage._enabledTables {return false}
        if _storage._submodeEntryPointChars != rhs_storage._submodeEntryPointChars {return false}
        if _storage._autoConvertHotkey != rhs_storage._autoConvertHotkey {return false}
        if _storage._useUserDictionary != rhs_storage._useUserDictionary {return false}
        if _storage._useDefaultZenzaiSettings != rhs_storage._useDefaultZenzaiSettings {return false}
        if _storage._zenzaiEnable != rhs_storage._zenzaiEnable {return false}
        if _storage._zenzaiInferLimit != rhs_storage._zenzaiInferLimit {return false}
        if _storage._zenzaiContextualMode != rhs_storage._zenzaiContextualMode {return false}
        if _storage._useZenzaiCustomWeight != rhs_storage._useZenzaiCustomWeight {return false}
        if _storage._zenzaiWeightPath != rhs_storage._zenzaiWeightPath {return false}
        if _storage._zenzaiBackendDeviceName != rhs_storage._zenzaiBackendDeviceName {return false}
        if _storage._zenzaiProfile != rhs_storage._zenzaiProfile {return false}
        if _storage._zenzaiTopic != rhs_storage._zenzaiTopic {return false}
        if _storage._zenzaiStyle != rhs_storage._zenzaiStyle {return false}
        if _storage._zenzaiPreference != rhs_storage._zenzaiPreference {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_Profile.AutoConvertMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AUTO_CONVERT_MODE_UNSPECIFIED\0\u{1}AUTO_CONVERT_DISABLED\0\u{1}AUTO_CONVERT_ALWAYS\0\u{1}AUTO_CONVERT_FOR_MULTIPLE_CHARS\0")
}

nonisolated extension Hazkey_Config_Profile.AuxTextMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AUX_TEXT_MODE_UNSPECIFIED\0\u{1}AUX_TEXT_DISABLED\0\u{1}AUX_TEXT_SHOW_ALWAYS\0\u{1}AUX_TEXT_SHOW_WHEN_CURSOR_NOT_AT_END\0")
}

nonisolated extension Hazkey_Config_Profile.SuggestionListMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SUGGESTION_LIST_MODE_UNSPECIFIED\0\u{1}SUGGESTION_LIST_DISABLED\0\u{1}SUGGESTION_LIST_SHOW_NORMAL_RESULTS\0\u{1}SUGGESTION_LIST_SHOW_PREDICTIVE_RESULTS\0")
}

nonisolated extension Hazkey_Config_Profile.SpecialConversionMode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_Profile.protoMessageName + ".SpecialConversionMode"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}comma_separated_number\0\u{3}mail_domain\0\u{1}calendar\0\u{1}time\0\u{3}roman_typography\0\u{3}unicode_codepoint\0\u{3}hazkey_version\0\u{3}relative_date\0\u{4}*halfwidth_katakana\0\u{3}extended_emoji\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._commaSeparatedNumber) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._mailDomain) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._calendar) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._time) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._romanTypography) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._unicodeCodepoint) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._hazkeyVersion) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self._relativeDate) }()
      case 50: try { try decoder.decodeSingularBoolField(value: &self._halfwidthKatakana) }()
      case 51: try { try decoder.decodeSingularBoolField(value: &self._extendedEmoji) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._commaSeparatedNumber {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._mailDomain {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._calendar {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._time {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._romanTypography {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._unicodeCodepoint {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._hazkeyVersion {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._relativeDate {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._halfwidthKatakana {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 50)
    } }()
    try { if let v = self._extendedEmoji {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 51)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_Profile.SpecialConversionMode, rhs: Hazkey_Config_Profile.SpecialConversionMode) -> Bool {
    if lhs._commaSeparatedNumber != rhs._commaSeparatedNumber {return false}
    if lhs._mailDomain != rhs._mailDomain {return false}
    if lhs._calendar != rhs._calendar {return false}
    if lhs._time != rhs._time {return false}
    if lhs._romanTypography != rhs._romanTypography {return false}
    if lhs._unicodeCodepoint != rhs._unicodeCodepoint {return false}
    if lhs._hazkeyVersion != rhs._hazkeyVersion {return false}
    if lhs._relativeDate != rhs._relativeDate {return false}
    if lhs._halfwidthKatakana != rhs._halfwidthKatakana {return false}
    if lhs._extendedEmoji != rhs._extendedEmoji {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_Profile.EnabledKeymap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_Profile.protoMessageName + ".EnabledKeymap"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}is_built_in\0\u{1}filename\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._isBuiltIn) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._filename) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._isBuiltIn {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._filename {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_Profile.EnabledKeymap, rhs: Hazkey_Config_Profile.EnabledKeymap) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._isBuiltIn != rhs._isBuiltIn {return false}
    if lhs._filename != rhs._filename {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_Profile.EnabledInputTable: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Hazkey_Config_Profile.protoMessageName + ".EnabledInputTable"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}is_built_in\0\u{1}filename\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._isBuiltIn) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._filename) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._isBuiltIn {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._filename {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_Profile.EnabledInputTable, rhs: Hazkey_Config_Profile.EnabledInputTable) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._isBuiltIn != rhs._isBuiltIn {return false}
    if lhs._filename != rhs._filename {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_GetConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_GetConfig, rhs: Hazkey_Config_GetConfig) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_SetConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SetConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}file_hashes\0\u{1}profiles\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.fileHashes) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.profiles) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileHashes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fileHashes, fieldNumber: 1)
    }
    if !self.profiles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.profiles, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_SetConfig, rhs: Hazkey_Config_SetConfig) -> Bool {
    if lhs.fileHashes != rhs.fileHashes {return false}
    if lhs.profiles != rhs.profiles {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_GetDefaultProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetDefaultProfile"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_GetDefaultProfile, rhs: Hazkey_Config_GetDefaultProfile) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_ClearAllHistory: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ClearAllHistory"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}profile_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.profileID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.profileID.isEmpty {
      try visitor.visitSingularStringField(value: self.profileID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ClearAllHistory, rhs: Hazkey_Config_ClearAllHistory) -> Bool {
    if lhs.profileID != rhs.profileID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_ReloadZenzaiModel: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ReloadZenzaiModel"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_ReloadZenzaiModel, rhs: Hazkey_Config_ReloadZenzaiModel) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_CurrentConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CurrentConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}file_hashes\0\u{1}profiles\0\u{3}available_keymaps\0\u{3}available_tables\0\u{4}\u{2}xdg_config_home_path\0\u{3}available_zenzai_backend_devices\0\u{3}zenzai_model_available\0\u{3}zenzai_model_path\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.fileHashes) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.profiles) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.availableKeymaps) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.availableTables) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.xdgConfigHomePath) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.availableZenzaiBackendDevices) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.zenzaiModelAvailable) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.zenzaiModelPath) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileHashes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fileHashes, fieldNumber: 1)
    }
    if !self.profiles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.profiles, fieldNumber: 2)
    }
    if !self.availableKeymaps.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.availableKeymaps, fieldNumber: 3)
    }
    if !self.availableTables.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.availableTables, fieldNumber: 4)
    }
    if !self.xdgConfigHomePath.isEmpty {
      try visitor.visitSingularStringField(value: self.xdgConfigHomePath, fieldNumber: 6)
    }
    if !self.availableZenzaiBackendDevices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.availableZenzaiBackendDevices, fieldNumber: 7)
    }
    if self.zenzaiModelAvailable != false {
      try visitor.visitSingularBoolField(value: self.zenzaiModelAvailable, fieldNumber: 8)
    }
    if !self.zenzaiModelPath.isEmpty {
      try visitor.visitSingularStringField(value: self.zenzaiModelPath, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_CurrentConfig, rhs: Hazkey_Config_CurrentConfig) -> Bool {
    if lhs.fileHashes != rhs.fileHashes {return false}
    if lhs.profiles != rhs.profiles {return false}
    if lhs.availableKeymaps != rhs.availableKeymaps {return false}
    if lhs.availableTables != rhs.availableTables {return false}
    if lhs.availableZenzaiBackendDevices != rhs.availableZenzaiBackendDevices {return false}
    if lhs.zenzaiModelAvailable != rhs.zenzaiModelAvailable {return false}
    if lhs.zenzaiModelPath != rhs.zenzaiModelPath {return false}
    if lhs.xdgConfigHomePath != rhs.xdgConfigHomePath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_GetLearningHistory: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetLearningHistory"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}profile_id\0\u{1}query\0\u{1}offset\0\u{1}limit\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.profileID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.query) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.offset) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.limit) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.profileID.isEmpty {
      try visitor.visitSingularStringField(value: self.profileID, fieldNumber: 1)
    }
    if !self.query.isEmpty {
      try visitor.visitSingularStringField(value: self.query, fieldNumber: 2)
    }
    if self.offset != 0 {
      try visitor.visitSingularUInt32Field(value: self.offset, fieldNumber: 3)
    }
    if self.limit != 0 {
      try visitor.visitSingularUInt32Field(value: self.limit, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_GetLearningHistory, rhs: Hazkey_Config_GetLearningHistory) -> Bool {
    if lhs.profileID != rhs.profileID {return false}
    if lhs.query != rhs.query {return false}
    if lhs.offset != rhs.offset {return false}
    if lhs.limit != rhs.limit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_LearningEntryKey: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LearningEntryKey"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reading\0\u{1}word\0\u{1}lcid\0\u{1}rcid\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.word) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.lcid) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.rcid) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 1)
    }
    if !self.word.isEmpty {
      try visitor.visitSingularStringField(value: self.word, fieldNumber: 2)
    }
    if self.lcid != 0 {
      try visitor.visitSingularUInt32Field(value: self.lcid, fieldNumber: 3)
    }
    if self.rcid != 0 {
      try visitor.visitSingularUInt32Field(value: self.rcid, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_LearningEntryKey, rhs: Hazkey_Config_LearningEntryKey) -> Bool {
    if lhs.reading != rhs.reading {return false}
    if lhs.word != rhs.word {return false}
    if lhs.lcid != rhs.lcid {return false}
    if lhs.rcid != rhs.rcid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_DeleteLearningEntries: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteLearningEntries"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}profile_id\0\u{1}entries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.profileID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.profileID.isEmpty {
      try visitor.visitSingularStringField(value: self.profileID, fieldNumber: 1)
    }
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_DeleteLearningEntries, rhs: Hazkey_Config_DeleteLearningEntries) -> Bool {
    if lhs.profileID != rhs.profileID {return false}
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_LearningHistoryEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LearningHistoryEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reading\0\u{1}word\0\u{1}lcid\0\u{1}rcid\0\u{1}count\0\u{3}last_used_unix_day\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.word) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.lcid) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.rcid) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.count) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.lastUsedUnixDay) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 1)
    }
    if !self.word.isEmpty {
      try visitor.visitSingularStringField(value: self.word, fieldNumber: 2)
    }
    if self.lcid != 0 {
      try visitor.visitSingularUInt32Field(value: self.lcid, fieldNumber: 3)
    }
    if self.rcid != 0 {
      try visitor.visitSingularUInt32Field(value: self.rcid, fieldNumber: 4)
    }
    if self.count != 0 {
      try visitor.visitSingularUInt32Field(value: self.count, fieldNumber: 5)
    }
    if self.lastUsedUnixDay != 0 {
      try visitor.visitSingularUInt32Field(value: self.lastUsedUnixDay, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_LearningHistoryEntry, rhs: Hazkey_Config_LearningHistoryEntry) -> Bool {
    if lhs.reading != rhs.reading {return false}
    if lhs.word != rhs.word {return false}
    if lhs.lcid != rhs.lcid {return false}
    if lhs.rcid != rhs.rcid {return false}
    if lhs.count != rhs.count {return false}
    if lhs.lastUsedUnixDay != rhs.lastUsedUnixDay {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_GetLearningHistoryResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetLearningHistoryResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entries\0\u{3}total_count\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.totalCount) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 1)
    }
    if self.totalCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.totalCount, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_GetLearningHistoryResult, rhs: Hazkey_Config_GetLearningHistoryResult) -> Bool {
    if lhs.entries != rhs.entries {return false}
    if lhs.totalCount != rhs.totalCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Hazkey_Config_DeleteLearningEntriesResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteLearningEntriesResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}deleted_count\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.deletedCount) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deletedCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.deletedCount, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_Config_DeleteLearningEntriesResult, rhs: Hazkey_Config_DeleteLearningEntriesResult) -> Bool {
    if lhs.deletedCount != rhs.deletedCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
